### PR TITLE
Improvements in the sx installer

### PR DESCRIPTION
**Pull request by PabloCastellano**
Installing obelisk from install-sx.sh works but the setup.sh script fails because of this regexp.
Someone please verify it's correct.

### CODE REVIEW

**Comment by PabloCastellano** [comment]
Output: https://gist.github.com/PabloCastellano/f1acd9d788acf9e597b9

**Comment by rdks** [comment]
@PabloCastellano just one minor remark:
`scripts/setup.sh:23` still says:
`echo " [+] Welcome to Obelisk worker and balancer daemon setup."`
You might want to remove the reference to balancer there, too.
Everything else looks fine to me.

**Comment by PabloCastellano** [comment]
Fixed that too.

There are still some references to the balancer in the documentation but I don't know what replaced obbalancer.

**Comment by evoskuil** [comment]
Just a heads up, I'm planning to move this repo to spesmilo shortly.

**Comment by evoskuil** [comment]
Please reopen against https://github.com/spesmilo/obelisk if this remains applicable.

**Pull request closed without merging**
